In [1]:
# Load Libraries
import cv2
import numpy as np
import pandas as pd
import open3d as o3d
from matplotlib import pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from sklearn import decomposition
from sklearn import datasets

In [2]:
# Load Room A, B pointcloud (x,y,z,R,G,B)
pcdA = o3d.io.read_point_cloud(r"C:\Users\...\PointCloud_A.ply")
pcdB = o3d.io.read_point_cloud(r"C:\Users\...\PointCloud_B.ply")

In [3]:
# Visualize the pointclouds
o3d.visualization.draw_geometries([pcdA])
o3d.visualization.draw_geometries([pcdB])

In [9]:
# Making 2 arrays, one with the points and one with the colors of the downsized pointcloud RoomA
colA = np.asarray(pcdA.colors)
pntA = np.asarray(pcdA.points)

In [10]:
# Print the arrays of the first pointcloud
print(pntA)
print(colA)
pntA.shape

[[-4.07730510e+00 -2.66569827e+00  2.82512383e+01]
 [ 2.75299057e-02  7.23286416e+00  2.35189946e+01]
 [ 2.95438359e+00 -4.07910893e+00  2.59515700e+01]
 ...
 [ 3.15025185e+00 -2.01338861e+00  2.75244183e+01]
 [ 1.87795589e+00 -5.87895844e+00  3.00412764e+01]
 [-2.59598453e-01 -1.64616011e+00  2.77417187e+01]]
[[0.68235294 0.6627451  0.65490196]
 [0.63529412 0.68235294 0.70980392]
 [0.66666667 0.57647059 0.50588235]
 ...
 [0.14117647 0.16470588 0.21176471]
 [0.4627451  0.52156863 0.6627451 ]
 [0.04705882 0.03921569 0.05882353]]


(812850, 3)

In [11]:
# Making 2 arrays, with the points and with the colors of the second point cloud
colB = np.asarray(pcdB.colors)
pntB = np.asarray(pcdB.points)

In [12]:
# Print the second pointcloud
print(pntB)
print(colB)
pntB.shape

[[-1.1263864   0.23776194 -4.2433877 ]
 [-1.2106786   0.14977331 -4.2309246 ]
 [-1.1944033   0.14402398 -4.2335453 ]
 ...
 [ 1.4890983   2.1237135   4.0051699 ]
 [ 1.456127    2.1367371   4.0007248 ]
 [ 1.4615676   2.1353354   4.0021071 ]]
[[0.25882353 0.21176471 0.15686275]
 [0.25490196 0.20784314 0.16078431]
 [0.25098039 0.20392157 0.15686275]
 ...
 [0.65882353 0.61176471 0.5254902 ]
 [0.77254902 0.74509804 0.68235294]
 [0.71764706 0.63921569 0.54509804]]


(700180, 3)

In [16]:
# Make the two arrays equal by reducing the number of the points of biggest one
pntAa = pntA[0:700180]
colAa = colA[0:700180]

In [ ]:
# As an alternative and more accurate solution it would be the padding method, creating new points using the mean values of the others. 

In [17]:
#merge the two pointclouds
new_pnt = pntAa + pntB
new_col = colAa + colB

In [18]:
#creating a new pointcloud with the merged points and colors
pcd_new = o3d.geometry.PointCloud()
pcd_new.points = o3d.utility.Vector3dVector(new_pnt)
pcd_new.colors = o3d.utility.Vector3dVector(new_col)
pcd_new.estimate_normals(search_param=o3d.geometry.KDTreeSearchParamHybrid(
        radius=0.001, max_nn=50))

True

In [20]:
# Vizualization the new pointcloud
o3d.visualization.draw_geometries([pcd_new])

In [21]:
# Create a file with the two pointclouds merged
o3d.io.write_point_cloud("RoomA+B.ply", pcd_new)

[Open3D WARNING] Write Ply clamped color value to valid range


True

In [22]:
# Creates a mesh from the pcd_new
mesh, densities = o3d.geometry.TriangleMesh.create_from_point_cloud_poisson(
    pcd_new, depth=8)

In [27]:
# Visualize the mesh
o3d.visualization.draw_geometries([mesh])